### PR TITLE
Linux stubdom support

### PR DESCRIPTION
**Pull request by HW42**
PR against this branch instead of https://github.com/QubesOS/qubes-core-admin/tree/core3-devel since your branch contains a bunch of fixes I needed while testing.

The option for minios stubdoms are currently left in to ease debugging.

### CODE REVIEW

**Comment by marmarek** [comment]
/cc @woju
Oh, sorry, I've rebased that branch, which resulted in a lot of conflicts. Please review only that last commit.

**Comment by woju** [comment]
Why the feature `'linux-stubdom'` is assumed to be `False` if not present? Aren't we switching to Linux-based stubdomains by default?

What happens to cmdline if vm.netvm is true and 'linux-stubdom' is present? The logic there causes it to be omitted from XML. Is that information passed somewhere else?

Otherwise, LGTM.

**Comment by marmarek** [comment]
> Why the feature 'linux-stubdom' is assumed to be False if not present? Aren't we switching to Linux-based stubdomains by default?

Yes, should be true by default. I'll change that in a separate commit.

> What happens to cmdline if vm.netvm is true and 'linux-stubdom' is present? The logic there causes it to be omitted from XML. Is that information passed somewhere else?

Yes, in that a case lwip is not used. Instead there is udhcpd with config built based on other xenstore entries (we do have shell there, so can generate config there easily). See https://github.com/marmarek/qubes-vmm-xen-stubdom-linux/blob/master/rootfs/init

**Comment by marmarek** [comment]
Hmm, shouldn't `features.check_with_template` be used instead of `features.get`?

**Comment by woju** [comment]
On Mon, May 15, 2017 at 05:45:41AM -0700, Marek Marczykowski-Górecki wrote:
> Hmm, shouldn't `features.check_with_template` be used instead of `features.get`?

I don't know. If you can have template and its appvm working both with and
without this feature, probably features.get is OK. If there is some
correlation (like extra package installed?), maybe check_with_template is good
idea.

I don't know how that stubdomain works, so I don't have any opinion.

**Comment by marmarek** [comment]
In principle it depends on OS installed there - most should work with either, but there might be exceptions. In some cases it may be also impossible to switch from one to another without some manual reconfiguration of that OS (like drivers installation).
So, there are cases when either version will work, but probably not all of them. In any case, check_with_template do allow choosing on per-VM basis.
Another story is how long, if at all, we want to keep mini-os-based stubdomain support. For 4.0 probably yes, to have some fallback in case of some problems with linux-based. But maybe not longer?

**Comment by woju** [comment]
On Mon, May 15, 2017 at 06:53:21AM -0700, Marek Marczykowski-Górecki wrote:
> In principle it depends on OS installed there - most should work with
> either, but there might be exceptions. In some cases it may be also
> impossible to switch from one to another without some manual reconfiguration
> of that OS (like drivers installation). So, there are cases when either
> version will work, but probably not all of them. In any case,
> check_with_template do allow choosing on per-VM basis.

I'm fine with check_with_template.

> Another story is how long, if at all, we want to keep mini-os-based
> stubdomain support. For 4.0 probably yes, to have some fallback in case of
> some problems with linux-based. But maybe not longer?

I dunno. I defer to your judgement. Are there any advantages to minios,
technical or otherwise, besides the fact that minios is well-tested and linux
not really? For example, is xen-devel more likely to be supportive?

**Comment by marmarek** [comment]
> I dunno. I defer to your judgement. Are there any advantages to minios, technical or otherwise, besides the fact that minios is well-tested and linux not really? For example, is xen-devel more likely to be supportive?

Yes, minios-based stubdomain is officially "supported". But this "supported" means fixing bugs we (or any of few others) its users find, but not backporting bugfixes from upstream qemu. Xen Project have a desire for a long time to ditch this ancient qemu fork and replace with upstream qemu on another unikernel. Nothing like this have happened yet...
On the other hand, linux-based stubdomain is just a Linux VM, running recent version of upstream qemu. The only custom part is some modifications to make work in stubdomain (instead of dom0).

**Comment by marmarek** [comment]
Cherry-picked to master.

**Pull request closed without merging**
